name: "Deploy To NekoWeb"

inputs:
  nekoweb-api-key:
    description: "Your NekoWeb API key."
    required: true
  nekoweb-domain:
    description: "Your NekoWeb domain to deploy to."
    required: true
  nekoweb-username:
    description: "Your NekoWeb username."
    required: true
  directory:
    description: "Which directory to upload?"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup
      uses: actions/setup-node@v4

    - name: Download Deployment Script
      run: git clone --depth 1 https://github.com/Pufikas/deploytonekoweb.git
      shell: bash

    - name: Install Dependencies
      working-directory: deploytonekoweb
      run: npm ci
      shell: bash

    - name: Deploy
      working-directory: deploytonekoweb
      env:
          APIKEY: ${{ inputs.nekoweb-api-key }}
          DOMAIN: ${{ inputs.nekoweb-domain }}
          USERNAME: ${{ inputs.nekoweb-username }}
          DIRECTORY: ${{ inputs.directory }}
      run: npm run deploy
      shell: bash